version: '3.8'
services:
  stat:
    build: stat
    image: ewm-stat-server
    container_name: ewm-stat-server
    ports:
      - "9090:9090"
    depends_on:
      - statdb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://statdb:5432/ewm-stat
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root


  statdb:
    image: postgres:13.7-alpine
    container_name: ewm-stat-db
    ports:
      - "6436:5432"
    environment:
      - POSTGRES_DB=ewm-stat
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  server:
    build: server
    image: ewm-server
    container_name: ewm-server
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ewm
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root


  db:
    image: postgis/postgis:15-3.3-alpine
    container_name: ewm-db

    ports:
      - "6435:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root