drop table if exists stats cascade;

create table if not exists stats
(
    stat_id            INTEGER GENERATED BY DEFAULT AS IDENTITY,
    stat_app           CHARACTER VARYING(200) not null,
    stat_uri           CHARACTER VARYING(500) not null,
    stat_ip            CHARACTER VARYING(200) not null,
    stat_timestamp     timestamp              not null,

    constraint stat_id primary key (stat_id)
);